apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-03-25T03:15:31Z
  generation: 1
  labels:
    app: blackbox
  name: blackbox
  namespace: ns-monitor
  resourceVersion: "26528041"
  selfLink: /apis/extensions/v1beta1/namespaces/ns-monitor/deployments/blackbox
  uid: 3f4b2b49-4eac-11e9-9fc9-525400694f9d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blackbox
    spec:
      containers:
      - image: xiaotech/blackbox-exporter
        imagePullPolicy: Always
        name: blackbox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/blackbox_exporter/
          name: config
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: master
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: blackbox-conf
        name: config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-03-25T03:15:31Z
  labels:
    app: blackbox
  name: blackbox
  namespace: ns-monitor
  resourceVersion: "15888303"
  selfLink: /api/v1/namespaces/ns-monitor/services/blackbox
  uid: 3f500697-4eac-11e9-9fc9-525400694f9d
spec:
  clusterIP: 10.96.9.193
  ports:
  - port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    app: blackbox
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
