---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-data-pvc
  namespace: ns-monitor
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
