apiVersion: v1
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
      http_post_2xx:
        prober: http
        http:
          method: POST
          headers:
            Content-Type: application/json
          body: '{"hmac":"","params":{"publicFundsKeyWords":"xxx"}}'
      http_post_2xx_blackbox_test:
        prober: http
        http:
          method: POST
          headers:
            Content-Type: application/json
          body: '{"FT": "123", "task_id": "123", "page": "123"}'
      
      tcp_connect:
        prober: tcp
      pop3s_banner:
        prober: tcp
        tcp:
          query_response:
          - expect: "^+OK"
          tls: true
          tls_config:
            insecure_skip_verify: false
      ssh_banner:
        prober: tcp
        tcp:
          query_response:
          - expect: "^SSH-2.0-"
      irc_banner:
        prober: tcp
        tcp:
          query_response:
          - send: "NICK prober"
          - send: "USER prober prober prober :prober"
          - expect: "PING :([^ ]+)"
            send: "PONG ${1}"
          - expect: "^:[^ ]+ 001"
      icmp:
        prober: icmp
kind: ConfigMap
metadata:
  creationTimestamp: 2019-03-25T03:15:31Z
  name: blackbox-conf
  namespace: ns-monitor
  resourceVersion: "23561782"
  selfLink: /api/v1/namespaces/ns-monitor/configmaps/blackbox-conf
  uid: 3f4cf3a0-4eac-11e9-9fc9-525400694f9d
