apiVersion: v1
data:
  rules.yml: |
    groups:
      - name: worker node alert
        rules:
        - alert: Node
          expr: up{job="worker node"} == 0
          for: 1m
          labels:
            severity: Fatal
          annotations:
            description: "{{ $labels.instance }} 无法连接"
        - alert: Memory
          expr: (1-node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)*100 > 85
          for: 3m
          labels:
            severity: Warning
          annotations:
            description: "{{ $labels.instance }} 内存使用率{{ $value }}% "
        - alert: CPU
          expr: avg(1-rate(node_cpu_seconds_total{mode="idle"}[1m])) by (instance) * 100  > 90
          for: 3m
          labels:
            severity: Warning
          annotations:
            description: "{{ $labels.instance }} CPU使用率{{ $value }}% "
        - alert: Disk
          expr: ( 1-node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} )* 100  > 80
          for: 3m
          labels:
            severity: Warning
          annotations:
            description: "{{ $labels.instance }} 磁盘使用率{{ $value }}% "
kind: ConfigMap
metadata:
  creationTimestamp: 2019-03-20T02:21:00Z
  name: prometheus-rules
  namespace: ns-monitor
  resourceVersion: "16806849"
  selfLink: /api/v1/namespaces/ns-monitor/configmaps/prometheus-rules
  uid: cdcc38c1-4ab6-11e9-9fc9-525400694f9d
